# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

use_modular_headers!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# Required: forces RNFB pods to build as static frameworks,
# resolving FIRAuthErrorCode / Firebase header issues with RN 0.84+
$RNFirebaseAsStaticFramework = true

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name.eql?('RNFBApp') || pod.name.eql?('RNFBAuth') ||
       pod.name.eql?('RNFBFirestore') || pod.name.eql?('RNFBStorage')
      def pod.build_type
        Pod::BuildType.static_library
      end
    end
  end
end

target 'SplitEasy' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    # Allow non-modular includes in framework modules (needed for Firebase + RNFB)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
  end
end
